### ISSUE TITLE
Librewolf Support

### ISSUE THREAD

**Issue by Enigma1309** [KiKaraage/ArcWTF#5]
Librewolf is same as firefox but with privacy features enabled, i installed this theme and everything seems to work out of the box.....sideberry, icons and everything else just worked fine...
except when i turned off Adaptive tab bar color in the extensions menu my config break kinda. in firefox if i turned off the adaptive tab bar color it just works see
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/024e9804-c134-4c8b-9119-921fc4841a5b)
everything seems to be perfect 

but when i do the same in librewolf
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/fe1bbce3-7895-4584-ac4d-334f5f2026f2)
the consisency seems to break, if i re-enable it just works, but i don't wanna use adaptive tabbar color always

#### your theme works when i install the setup, but it breaks after enabling and disabling the adaptive tabbar color.

Also is there any way to turn this off, this only gets enabled if i use adaptive tabbar color (i'm on linux Hyprland i don't  want close button like windows)
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/2dd20762-5eb9-4483-9f9c-dee3a13f912b)

Sorry for my bad english
Thanks in advance ❤️

**Comment by KiKaraage** [comment]
1. For navbar color issues: Have you tried other themes (outside of Firefox default dark/light/system themes)? You can also turn custom settings CSS off ( in about:config), restart, turn it on again, and restart Librewolf again.
2. For the window controls: Try [this CSS](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/window_control_force_linux_system_style.css). Put it on chrome/tweaks, and add this command on your userchrome.css:

```
@import url("tweaks/window_control_force_linux_system_style.css");
```

**Comment by Enigma1309** [comment]
okay i've made a new profile in librewolf and just installed the Adaptive Tab-bar color extension , whenever i turned it on it automatically spawned an windows like control( close, maximize, minimize ) so i think i have to make a issue there.


But when i turned on and off the extension it resumes it's older state (i.e same color as default) am i missing out on something?

i tried to recreate your config in the newprofile and i got to the same result ( broken color) and it kinda disappoints me 

i don't have much knowledge about how to fix this :\ anyone please help me out.

**Comment by KiKaraage** [comment]
Please tell me if you have done the 2nd step. Screenshot(s) would be appreciated!

Hmmm I have to try Librewolf.....

**Comment by Enigma1309** [comment]
Yes it works on firefox

> in firefox if i turned off the adaptive tab bar color and it just works see
> ![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/573d9a7b-daf9-4adc-921f-4648dd38184b)
> everything seems to be perfect


yes i did the second step and that isn't the problem anymore, i think the issue of windows button is due to the extension itself

Here are the steps if i ain't doing anything wrong

1) Creaating profile 
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/3f4141dc-6b6a-4932-9ccc-29e657601e57)

2) Launching bare profile
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/0a45cc99-5db6-4ccc-8d3c-67c575a3baad)

3) Enabling userchrome.css customization (it's same as about:config)
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/a82b8bf2-6cad-4a8a-aa62-ed971149e73a)

4) Installing Necessary Extensions
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/34d8c7c2-eb9e-41e7-a80f-89a1a046b2bf)

5) Configuring userchrometoggle
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/6c5672a4-595c-431b-8176-e269f07b4e0f)

6) Importing Sideberry CSS
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/15028457-ccad-48be-8966-e815db80ef4b)

7) Still looks the same 
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/ca0e4e22-701e-4449-b607-71c11292ed78)

**Comment by Enigma1309** [comment]
Here is a short video demonstrating the effect

https://github.com/KiKaraage/ArcWTF/assets/94917588/ef80985c-038e-4963-a2ca-fec56374a5f4

**Comment by LuanderFarias** [comment]
i have the same problem when using more than one window. as far as i've researched it's because of the sidebery extension, since it actively searches for the color of the browser window but it takes some seconds and get desincronized from the frame. i'm still looking for a fix.

**Comment by Enigma1309** [comment]
Hey i think i found the cause of the problem, it'a happening when the LibreWolf color-scheme is set to default

![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/90da4768-3654-4a6d-b240-98cbd1053fc1)


when setting it to the dark or light it automatically works, but sideberry css seems to have some issues with the system auto theme in LibreWolf

![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/ed2e866d-4a0d-487d-819c-81bf9af9d414)
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/24550c7b-5466-4afb-a37a-60ba39e5ee82)



IDK why is this happening but i've narrowed down my approach to this problem as sideberry not able to diffrentiate auto theme

**Comment by LuanderFarias** [comment]
found a temporary solution? https://github.com/linonetwo/browser-adaptation-dynamic-theme

**Comment by KiKaraage** [comment]
Yeah that's why I suggest not to use Firefox default system theme.

Also, after nonactivating Adaptive Tab Bar Color Firefox default theme will automatically applied, so just apply other theme and the issue with Sidebery is solved

About the window-controls.... Sadly I don't see settings related to window control buttons on the addon option, so you might want to use other addons as advised above. You can also submit an issue on [their Github](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/issues).... The author are currently busy tho.

Oh yeah, hi and thank you @LuanderFarias for replying! May I know the setup you're using right now? (OS & Firefox version)

**Comment by LuanderFarias** [comment]
thanks for the ping. i'm using a windows firefox version 122.0.

still working on a possible solution for the problem with the color and etc... but it's hard since i'm focusing more on arcfox lol. So far i've discovered that the extension pushes the color from the main page header but pass some filters before applying and using it. also, i've been thinking about using other things than the extension, maybe a user.js or something like... but nothing much on the moment...

**Comment by Enigma1309** [comment]
i am still unable to find the fix, this doesn't solve it either

**Comment by LuanderFarias** [comment]
yeah me too. don't know why this got the complete status without any warning :(

**Comment by Enigma1309** [comment]
one solution to this issue may be create a firefox color config and use it, since sideberry reacts well on firefox color extension

**Comment by Enigma1309** [comment]
![image](https://github.com/KiKaraage/ArcWTF/assets/94917588/4e2e3933-7ad3-4034-9ed8-dc867ffa21bc)


i did these changes and the buttons got disappeared, but how do i trim the excess space, ther isn't any flexible space either but i can't get it to be removed 😬

**Comment by KiKaraage** [comment]
You can customize it from [hide-tabs-bar.css line 125](https://github.com/KiKaraage/ArcWTF/blob/69ee325b7168c0afac862a35280ed309d48a36c5/tweaks/hide-tabs-bar.css#L125) for Linux

![gambar](https://github.com/KiKaraage/ArcWTF/assets/10529881/bb9c4df0-7821-4dbf-922e-b7f28203409c)

But to be precise, you can inspect it by yourself with Browser Toolbox (ctrl + shift + alt + i). Let me know your result and if there's something I can apply to the codes.

**Comment by Enigma1309** [comment]
+ var(--uc-titlebar-drag-space)) 

removing this fixes this issue for me 🫶

also i wanna remind that in the latest version the tabs aren't showing in the private window , downgrading fixes it temporarily

**Comment by KiKaraage** [comment]
> ` + var(--uc-titlebar-drag-space))` removing this fixes this issue for me 🫶

I wonder if this is applicable to all Linux case, since default value is 40px.

> also i wanna remind that in the latest version the tabs aren't showing in the private window , downgrading fixes it temporarily

Can you show it with screenshots? I haven't been able to grasp this problem, and private window works good enough for me (of course with Sidebery and Userchrome Toggle disabled on private, so the horizontal tabs won't be hidden).

**Comment by Enigma1309** [comment]
i was recording the steps to reproduce and now , It seems to work idk what was causing this 😐

**Comment by KiKaraage** [comment]
Alright, I'm looking for comments from more Linux users before adding it to the main repo 👍
